# Generated by Django 3.1.4 on 2020-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='visit_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
