# Generated by Django 3.1.4 on 2021-01-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0004_auto_20210101_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=50),
        ),
    ]
